Attempt to fix ctest/ftest for Intel Compiler.

diff --git a/Makefile.inc b/Makefile.inc
--- a/Makefile.inc
+++ b/Makefile.inc
@@ -299,16 +299,16 @@ uniqmov = $(if $(filter $($2),$($1)),$(call uniqadd,$1,$2,$3),$($1))
 
 ctest = $(if $1,$(if $(shell INFILE=$$($(MKTEMP) /tmp/.libxs_XXXXXX.c) && \
   echo "int main(void) { return 0; }" > $${INFILE} && if [ "$3" ]; \
-  then $1 -c $${INFILE} -o $${INFILE}.o 2>/dev/null >/dev/null && \
-    if [ "$$($1 $2 $${INFILE}.o -o $${INFILE}.x 2>&1)" ]; then false; fi; \
-  else $1 $2 $${INFILE} -o $${INFILE}.x 2>/dev/null >/dev/null; fi && echo "OK"; \
-  rm -f /tmp/$$(basename $${INFILE} .c).* .libxs_??????.c.* 2>/dev/null),$2))
+  then $1 -c $${INFILE} -o $${INFILE}.o >/dev/null && \
+    if [ "$$($1 $2 $${INFILE}.o -o $${INFILE}.x >/dev/null)" ]; then false; fi; \
+  else $1 $2 $${INFILE} -o $${INFILE}.x >/dev/null; fi 2>&1 || echo "FAILED"; \
+  rm -f /tmp/$$(basename $${INFILE} .c).* .libxs_??????.c.* 2>/dev/null),$(NULL),$2))
 # INFILE cannot use leading dot when used with certain F-compiler
 ftest = $(if $1,$(if $(shell INFILE=$$($(MKTEMP) /tmp/_libxs_XXXXXX.f) && \
   printf "      PROGRAM test\n      END PROGRAM\n" > $${INFILE} && if [ "$3" ]; \
-  then $1 -c $${INFILE} -o $${INFILE}.o 2>/dev/null >/dev/null && \
-    if [ "$$($1 $2 $${INFILE}.o -o $${INFILE}.x 2>&1)" ]; then false; fi; \
-  else $1 $2 $${INFILE} -o $${INFILE}.x 2>/dev/null >/dev/null; fi || echo "FAILED"; \
+  then $1 -c $${INFILE} -o $${INFILE}.o >/dev/null && \
+    if [ "$$($1 $2 $${INFILE}.o -o $${INFILE}.x >/dev/null)" ]; then false; fi; \
+  else $1 $2 $${INFILE} -o $${INFILE}.x >/dev/null; fi 2>&1 || echo "FAILED"; \
   rm -f /tmp/$$(basename $${INFILE} .f).* _libxs_??????.f.* 2>/dev/null),$(NULL),$2))
 
 ldclib = $(if $1,$(call ctest,$1 $2,-l$(strip $3)))
